name: Plagiarism Check

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run CPD (Copy-Paste Detector)
        uses: pmd/pmd-github-action@v2  
        with:
          sourcePath: '.'  
          rulesets: "category/cpp/design/cpd.xml"

      - name: Upload CPD report
        uses: actions/upload-artifact@v3
        with:
          name: cpd-report
          path: pmd-cpd.txt  
