name: Plagiarism Check

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run CPD
        uses: pmd/pmd-github-action@latest # Use the latest version 
        with:
          sourcePath: '.' 
      - name: Upload CPD report
        uses: actions/upload-artifact@v3
        with:
          name: cpd-report
          path: cpd.txt
