name: Moss Code Style Check

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  moss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Moss
        run: |
          sudo apt-get update
          sudo apt-get install -y perl
          wget http://theory.stanford.edu/~aiken/moss/moss.pl
          chmod +x moss.pl

      - name: Run Moss
        run: |
          ./moss.pl -l cpp -d $(find . -name "*.cpp") > moss_results.txt

      - name: Upload Moss results
        uses: actions/upload-artifact@v3
        with:
          name: moss-results
          path: moss_results.txt
