name: MossPlagiarismChecker

on:
  push:
    branches:
      - main

jobs:
  moss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python and mosspy
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install mosspy

      - name: Run Moss using mosspy
        run: |
          python3 -c "
          from mosspy import Moss
          m = Moss('739591289', 'cpp')  # Replace with your Moss ID
          for file in $(find . -name '*.cpp'):
            m.addFile(file)
          url = m.send()
          print(url)  # Print the Moss results URL
          " > moss_results.txt

      - name: Upload Moss results
        uses: actions/upload-artifact@v3
        with:
          name: moss-results
          path: moss_results.txt
